Fix tests

diff --git a/test b/test
--- a/test
+++ b/test
@@ -95,25 +95,66 @@ do
 	echo -e "\tTesting ${PURPLE}${current_test}${NC}..."
 
 	src="${file}"
-	expected="$current_test.expected"
+	expected_stdout="$current_test.expected.stdout"
+	expected_stderr="$current_test.expected.stderr"
 
-	if [ ! -f $expected ]
+	if [ ! -f $expected_stdout ]
 	then
-		echo -e "\t${RED}Missing expected output, ignored${NC}"
+		echo -e "\t${RED}Missing expected_stdout, ignored${NC}"
 		echo
 		continue
 	fi
 
-	output=$(./$doc_exec $src)
-	exp=$(cat $expected)
-
-	if [ "$output" != "$exp" ]
+	if [ ! -f $expected_stderr ]
 	then
-		echo -e "\t${RED}Error. The output is not the one expected:${NC}"
+		echo -e "\t${RED}Missing expected_stderr, ignored${NC}"
+		echo
+		continue
+	fi
+
+	rm -f "/tmp/stderr"
+	output=$(./$doc_exec $src 2> /tmp/stderr)
+	status=$(echo $?)
+	err=$(cat /tmp/stderr)
+	exp_stdout=$(cat $expected_stdout)
+	exp_stderr=$(cat $expected_stderr)
+
+	if [ "$output" != "$exp_stdout" ]
+	then
+		echo -e "\t${RED}Error. The output (stdout) is not the one expected:${NC}"
 		echo $output
 		let errors++
 	else
 		echo -e "\t${GREEN}Test passed successfully!${NC}"
+	fi
+	if [ "$err" != "$exp_stderr" ]
+	then
+		echo -e "\t${RED}Error. The error output (stderr) is not the one expected:${NC}"
+		echo $err
+		let errors++
+	else
+		echo -e "\t${GREEN}Test passed successfully!${NC}"
+	fi
+
+	if [ "$status" == "0" ]
+	then
+		if [[ $err = *[!\ ]* ]]
+		then
+			echo -e "\t${RED}Error. The error output (stderr) should be empty if the program successed:${NC}"
+			echo $err
+			let errors++
+		else
+			echo -e "\t${GREEN}Test passed successfully!${NC}"
+		fi
+	else
+		if [[ $err = *[!\ ]* ]]
+		then
+			echo -e "\t${GREEN}Test passed successfully!${NC}"
+		else
+			echo -e "\t${RED}Error. The error output (stderr) should be empty if the program successed:${NC}"
+			echo $err
+			let errors++
+		fi
 	fi
 	echo
 done
